export const date = [
  {
    id: 1,
    month: 11,
    date: 21,
    day: "월",
    matchDateFirst: "11.21.",
    matchDateSecond: "",
    matchDateThird: "",
    matchCount: 2,
  },
  {
    id: 2,
    month: 11,
    date: 22,
    day: "화",
    matchDateFirst: "11.22.",
    matchDateSecond: "",
    matchDateThird: "",
    matchCount: 4,
  },
  {
    id: 3,
    month: 11,
    date: 23,
    day: "수",
    matchDateFirst: "11.23.",
    matchDateSecond: "",
    matchDateThird: "",
    matchCount: 4,
  },
  {
    id: 4,
    month: 11,
    date: 24,
    day: "목",
    matchDateFirst: "11.24.",
    matchDateSecond: "",
    matchDateThird: "",
    matchCount: 4,
  },
  {
    id: 5,
    month: 11,
    date: 25,
    day: "금",
    matchDateFirst: "11.25.",
    matchDateSecond: "11.25.",
    matchDateThird: "",
    matchCount: 4,
  },
  {
    id: 6,
    month: 11,
    date: 26,
    day: "토",
    matchDateFirst: "",
    matchDateSecond: "11.26.",
    matchDateThird: "",
    matchCount: 4,
  },
  {
    id: 7,
    month: 11,
    date: 27,
    day: "일",
    matchDateFirst: "",
    matchDateSecond: "11.27.",
    matchDateThird: "",
    matchCount: 4,
  },
  {
    id: 8,
    month: 11,
    date: 28,
    day: "월",
    matchDateFirst: "",
    matchDateSecond: "11.28.",
    matchDateThird: "",
    matchCount: 4,
  },
  {
    id: 9,
    month: 11,
    date: 29,
    day: "화",
    matchDateFirst: "",
    matchDateSecond: "11.29.",
    matchDateThird: "",
    matchCount: 2,
  },
  {
    id: 10,
    month: 11,
    date: 30,
    day: "수",
    matchDateFirst: "",
    matchDateSecond: "",
    matchDateThird: "11.30.",
    matchCount: 4,
  },
  {
    id: 11,
    month: 12,
    date: 1,
    day: "목",
    matchDateFirst: "",
    matchDateSecond: "",
    matchDateThird: "12.01.",
    matchCount: 4,
  },
  {
    id: 12,
    month: 12,
    date: 2,
    day: "금",
    matchDateFirst: "",
    matchDateSecond: "",
    matchDateThird: "12.02.",
    matchCount: 4,
  },
];

export const matchInfo = [
  {
    id: 1,
    month: 11,
    date: 21,
    time: "01:00",
    group: "A조 예선",
    matchDateFirst: "11.21.",
  },
  {
    id: 2,
    month: 11,
    date: 21,
    time: "22:00",
    group: "B조 예선",
    matchDateFirst: "11.21.",
  },
  {
    id: 3,
    month: 11,
    date: 22,
    time: "01:00",
    group: "A조 예선",
    matchDateFirst: "11.22.",
  },
  {
    id: 4,
    month: 11,
    date: 22,
    time: "04:00",
    group: "B조 예선",
    matchDateFirst: "11.22.",
  },
  {
    id: 5,
    month: 11,
    date: 22,
    time: "19:00",
    group: "C조 예선",
    matchDateFirst: "11.22.",
  },
  {
    id: 6,
    month: 11,
    date: 22,
    time: "22:00",
    group: "D조 예선",
    matchDateFirst: "11.22.",
  },
  {
    id: 7,
    month: 11,
    date: 23,
    time: "01:00",
    group: "C조 예선",
    matchDateFirst: "11.23.",
  },
  {
    id: 8,
    month: 11,
    date: 23,
    time: "04:00",
    group: "D조 예선",
    matchDateFirst: "11.23.",
  },
  {
    id: 9,
    month: 11,
    date: 23,
    time: "19:00",
    group: "F조 예선",
    matchDateFirst: "11.23.",
  },
  {
    id: 10,
    month: 11,
    date: 23,
    time: "22:00",
    group: "E조 예선",
    matchDateFirst: "11.23.",
  },
  {
    id: 11,
    month: 11,
    date: 24,
    time: "01:00",
    group: "E조 예선",
    matchDateFirst: "11.24.",
  },
  {
    id: 12,
    month: 11,
    date: 24,
    time: "04:00",
    group: "F조 예선",
    matchDateFirst: "11.24.",
  },
  {
    id: 13,
    month: 11,
    date: 24,
    time: "19:00",
    group: "G조 예선",
    matchDateFirst: "11.24.",
  },
  {
    id: 14,
    month: 11,
    date: 24,
    time: "22:00",
    group: "H조 예선",
    matchDateFirst: "11.24.",
  },
  {
    id: 15,
    month: 11,
    date: 25,
    time: "01:00",
    group: "H조 예선",
    matchDateFirst: "11.25.",
  },
  {
    id: 16,
    month: 11,
    date: 25,
    time: "04:00",
    group: "G조 예선",
    matchDateFirst: "11.25.",
  },
  {
    id: 17,
    month: 11,
    date: 25,
    time: "19:00",
    group: "B조 예선",
    matchDateSecond: "11.25.",
  },
  {
    id: 18,
    month: 11,
    date: 25,
    time: "22:00",
    group: "A조 예선",
    matchDateSecond: "11.25.",
  },
  {
    id: 19,
    month: 11,
    date: 26,
    time: "01:00",
    group: "A조 예선",
    matchDateSecond: "11.26.",
  },
  {
    id: 20,
    month: 11,
    date: 26,
    time: "04:00",
    group: "B조 예선",
    matchDateSecond: "11.26.",
  },
  {
    id: 21,
    month: 11,
    date: 26,
    time: "19:00",
    group: "D조 예선",
    matchDateSecond: "11.26.",
  },
  {
    id: 22,
    month: 11,
    date: 26,
    time: "22:00",
    group: "C조 예선",
    matchDateSecond: "11.26.",
  },
  {
    id: 23,
    month: 11,
    date: 27,
    time: "01:00",
    group: "D조 예선",
    matchDateSecond: "11.27.",
  },
  {
    id: 24,
    month: 11,
    date: 27,
    time: "04:00",
    group: "C조 예선",
    matchDateSecond: "11.27.",
  },
  {
    id: 25,
    month: 11,
    date: 27,
    time: "19:00",
    group: "E조 예선",
    matchDateSecond: "11.27.",
  },
  {
    id: 26,
    month: 11,
    date: 27,
    time: "22:00",
    group: "F조 예선",
    matchDateSecond: "11.27.",
  },
  {
    id: 27,
    month: 11,
    date: 28,
    time: "01:00",
    group: "F조 예선",
    matchDateSecond: "11.28.",
  },
  {
    id: 28,
    month: 11,
    date: 28,
    time: "04:00",
    group: "E조 예선",
    matchDateSecond: "11.28.",
  },
  {
    id: 29,
    month: 11,
    date: 28,
    time: "19:00",
    group: "G조 예선",
    matchDateSecond: "11.28.",
  },
  {
    id: 30,
    month: 11,
    date: 28,
    time: "22:00",
    group: "H조 예선",
    matchDateSecond: "11.28.",
  },
  {
    id: 31,
    month: 11,
    date: 29,
    time: "01:00",
    group: "G조 예선",
    matchDateSecond: "11.29.",
  },
  {
    id: 32,
    month: 11,
    date: 29,
    time: "04:00",
    group: "H조 예선",
    matchDateSecond: "11.29.",
  },
  {
    id: 33,
    month: 11,
    date: 30,
    time: "00:00",
    group: "A조 예선",
    matchDateThird: "11.30.",
  },
  {
    id: 34,
    month: 11,
    date: 30,
    time: "00:00",
    group: "A조 예선",
    matchDateThird: "11.30.",
  },
  {
    id: 35,
    month: 11,
    date: 30,
    time: "04:00",
    group: "B조 예선",
    matchDateThird: "11.30.",
  },
  {
    id: 36,
    month: 11,
    date: 30,
    time: "04:00",
    group: "B조 예선",
    matchDateThird: "11.30.",
  },
  {
    id: 37,
    month: 12,
    date: "01",
    time: "00:00",
    group: "D조 예선",
    matchDateThird: "12.01.",
  },
  {
    id: 38,
    month: 12,
    date: "01",
    time: "00:00",
    group: "D조 예선",
    matchDateThird: "12.01.",
  },
  {
    id: 39,
    month: 12,
    date: "01",
    time: "04:00",
    group: "C조 예선",
    matchDateThird: "12.01.",
  },
  {
    id: 40,
    month: 12,
    date: "01",
    time: "04:00",
    group: "C조 예선",
    matchDateThird: "12.01.",
  },
  {
    id: 41,
    month: 12,
    date: "02",
    time: "00:00",
    group: "F조 예선",
    matchDateThird: "12.02.",
  },
  {
    id: 42,
    month: 12,
    date: "02",
    time: "00:00",
    group: "F조 예선",
    matchDateThird: "12.02.",
  },
  {
    id: 43,
    month: 12,
    date: "02",
    time: "04:00",
    group: "E조 예선",
    matchDateThird: "12.02.",
  },
  {
    id: 44,
    month: 12,
    date: "02",
    time: "04:00",
    group: "E조 예선",
    matchDateThird: "12.02.",
  },
];

export const article = [
  {
    id: 1,
    img: "image/article_1.jpeg",
    text: "'포르투갈엔 비상, 한국엔 호재' 캡틴 호날두, 장염으로 '훈련 결장'",
    subText: "스포츠조선",
  },
  {
    id: 2,
    img: "image/article_2.jpeg",
    text: `손흥민, ESPN 카타르WC 파워랭킹 13위..."국가 희망 짊어진 슈퍼스타"`,
    subText: "이데일리",
  },
  {
    id: 3,
    img: "image/article_3.jpeg",
    text: `'별풍선 받아요' BJ 데뷔 예정 국대 감독`,
    subText: "골닷컴",
  },
  {
    id: 4,
    img: "image/article_4.jpeg",
    text: `이청용의 소신발언, "선배들의 '특정 선수' 언급 자제해야..."`,
    subText: "마이데일리",
  },
  {
    id: 5,
    img: "image/article_5.jpeg",
    text: `[카타르 NOW] '메시 라스트 댄스' 아르헨티나, 월드컵 최종 평가젼 5-0 대승`,
    subText: "스포티비뉴스",
  },
  {
    id: 6,
    img: "image/article_6.jpeg",
    text: `[카타르 NOW]'마스크'와 친분 쌓는 손흥민, 폭발적 열정이 출전을 부른다`,
    subText: "스포티비뉴스",
  },
  {
    id: 7,
    img: "image/article_7.jpeg",
    text: `마스크 손, ESPN 선정 월드컵 베스트 13위... 亞 유일, H조 최고`,
    subText: "서울신문",
  },
  {
    id: 8,
    img: "image/article_8.jpeg",
    text: `[카타르 ON]벤투호 '막내즈'에게 물었습니다, 이번 대회 한국 첫 골의 주인공은?`,
    subText: "스포츠조선",
  },
  {
    id: 9,
    img: "image/article_9.jpeg",
    text: `안정환, 이강인 실력은 의심 없지만... "벤투는 기용도 안할 것"`,
    subText: "OSEN",
  },
  {
    id: 10,
    img: "image/article_10.jpeg",
    text: `몸 풀린 메시…아르헨, 최종 평가전서 UAE 5-0 대파`,
    subText: "헤럴드경제",
  },
];

export const navData = [
  { id: 1, path: "/home", name: "홈" },
  { id: 2, path: "/news", name: "뉴스" },
  { id: 3, path: "/", name: "일정" },
  { id: 4, path: "/countries", name: "참가국" },
  { id: 5, path: "/fifa", name: "FIFA" },
];

export const listData = [
  { id: 1, path: "/", name: "전체" },
  { id: 2, path: "/league", name: "조별리그" },
  { id: 3, path: "/tournament", name: "토너먼트" },
];
